require 'sinatra/base'
require 'sinatra'
require 'bcrypt'
require 'sinatra/reloader'
require 'sequel'
require 'rotp'
require 'digest'
require_relative 'private_methods.rb'
DB = Sequel.sqlite 'db\database.db'
